MASPRNG: primes/primes_32.cpp File Reference
primes_32.cpp File Reference
Functions
static int init_prime_32 ()
int getprime_32 (int need, int *prime_array, int offset)
Variables
static int primes [NPRIMES]
Function Documentation
int getprime_32 (int need, int * prime_array, int offset)
Definition at line 44 of file primes_32.cpp.
References init_prime_32(), prime_list_32, and primes.
Referenced by LCG::init_rng(), and VLCG::init_rng().
 {
     static int initiallized = NO, num_prime;
     int largest;
     int i, isprime, index, obtained = 0;
     if (need <= 0) {
         fprintf(stderr, "WARNING: Number of primes needed = %d < 1; None returned\n", need);
         return 0;
     }
     if (offset < 0) {
         fprintf(stderr, "WARNING: Offset of prime = %d < 1; None returned\n", offset);
         return 0;
     }
     if (offset+need-1 < PRIMELISTSIZE1) {
         memcpy(prime_array, prime_list_32 + offset, need * sizeof(int));
         return need;
     }
     if (!initiallized) {
         num_prime = init_prime_32();
         largest = MAXPRIME;
         initiallized = YES;
     }
     if (offset > MAXPRIMEOFFSET) {
         fprintf(stderr, "WARNING: generator has branched maximum number of times, independence of generators no longer guaranteed");
         offset = offset % MAXPRIMEOFFSET;
     }
     /* search table for previous prime */
     if (offset < PRIMELISTSIZE1) {
         largest = prime_list_32[offset] + 2;
         offset = 0;
     }
     else {
         index = (int)((offset-PRIMELISTSIZE1+1)/STEP) + PRIMELISTSIZE1 -  1;
         largest = prime_list_32[index] + 2;
         offset -= (index-PRIMELISTSIZE1+1)*STEP + PRIMELISTSIZE1 - 1;
     }
     while (need > obtained && largest > MINPRIME) {
         isprime = YES;
         largest -= 2;
         for (i = 0; i < num_prime; ++i)
             if (largest%primes[i] == 0) {
                 isprime = NO;
                 break;
             }
         if (isprime == YES && offset > 0)
             offset--;
         else if (isprime == YES)
             prime_array[obtained++] = largest;
     }
     if (need > obtained)
         fprintf(stderr, "ERROR: Insufficient number of primes: needed %d, obtained %d\n", need, obtained);
     return obtained;
 }
static int init_prime_32 () static
Definition at line 18 of file primes_32.cpp.
References primes.
Referenced by getprime_32().
 {
     int i, j, obtained = 0, isprime;
     for (i = 3; i < MINPRIME; i += 2) {
         isprime = YES;
         for (j = 0; j < obtained; ++j) {
             if (i % primes[j] == 0) {
                 isprime = NO;
                 break;
             }
             else if (primes[j]*primes[j] > i)
                 break;
         }
         if (isprime == YES) {
             primes[obtained] = i;
             obtained++;
         }
     }
     return obtained;
 }
Variable Documentation
int primes[NPRIMES] static
Definition at line 15 of file primes_32.cpp.
Referenced by getprime_32(), init_prime_32(), and main_gen().