MASPRNG: masprng.h File Reference
masprng.h File Reference
Functions
SPRNG * selectType (const int)
VSPRNG * selectTypeSIMD (const int)
Function Documentation
SPRNG* selectType (const int)
Interface used to create RNG instances.
Definition at line 13 of file masprng.cpp.
References SPRNG_LCG.
Referenced by check_gen(), and main_gen().
 {
     SPRNG *rng = NULL;
     switch (typenum) {
         //case SPRNG_LFG: rng = new LFG();
         //    break;
         case SPRNG_LCG: rng = new LCG();
             break;
         //case SPRNG_LCG64: rng = new LCG64();
         //    break;
         //case SPRNG_CMRG: rng = new CMRG();
         //    break;
         //case SPRNG_MLFG: rng = new MLFG();
         //    break;
         //case SPRNG_PMLCG: rng = new PMLCG();
         //    break;
         default: printf("ERROR: invalid RNG generator type.\n");
     }
     return rng;
 }
VSPRNG* selectTypeSIMD (const int)
Definition at line 47 of file masprng.cpp.
References SPRNG_LCG.
Referenced by check_gen(), and main_gen().
 {
     VSPRNG *rng = NULL;
     switch (typenum) {
         //case SPRNG_LFG: rng = new VLFG();
         //    break;
         case SPRNG_LCG: rng = new VLCG();
             break;
         //case SPRNG_LCG64: rng = new VLCG64();
         //    break;
         //case SPRNG_CMRG: rng = new VCMRG();
         //    break;
         //case SPRNG_MLFG: rng = new VMLFG();
         //    break;
         //case SPRNG_PMLCG: rng = new VPMLCG();
         //    break;
         default: printf("ERROR: invalid RNG generator type.\n");
     }
     return rng;
 }