MASPRNG: SPRNG Class Reference
SPRNG Class Reference abstract
Interface (pure abstract class) used as base class for RNG types.
#include <sprng.h>
Public Member Functions
virtual ~SPRNG ()
virtual int init_rng (int, int, int, int)=0
virtual int get_rn_int ()=0
virtual float get_rn_flt ()=0
virtual double get_rn_dbl ()=0
virtual int get_seed_rng () const =0
virtual unsigned long int get_ngens () const =0
virtual int get_prime () const =0
virtual unsigned long int get_seed () const =0
virtual unsigned long int get_multiplier () const =0
virtual int get_seed () const =0
virtual int get_multiplier () const =0
Detailed Description
Interface (pure abstract class) used as base class for RNG types.
Methods that are virtual require each derived class to define these methods.
Definition at line 32 of file sprng.h.
Constructor & Destructor Documentation
virtual SPRNG::~SPRNG () inline virtual
virtual destructor allows polymorphism to invoke derived destructors
Definition at line 35 of file sprng.h.
References get_multiplier(), get_ngens(), get_prime(), get_rn_dbl(), get_rn_flt(), get_rn_int(), get_seed(), get_seed_rng(), and init_rng().
Member Function Documentation
virtual unsigned long int SPRNG::get_multiplier () const pure virtual
Implemented in LCG, and LCG.
Referenced by main_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
virtual int SPRNG::get_multiplier () const pure virtual
Implemented in LCG, and LCG.
virtual unsigned long int SPRNG::get_ngens () const pure virtual
Implemented in LCG.
Referenced by ~SPRNG(), and VSPRNG::~VSPRNG().
virtual int SPRNG::get_prime () const pure virtual
Implemented in LCG.
Referenced by main_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
virtual double SPRNG::get_rn_dbl () pure virtual
Implemented in LCG.
Referenced by check_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
virtual float SPRNG::get_rn_flt () pure virtual
Implemented in LCG.
Referenced by check_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
virtual int SPRNG::get_rn_int () pure virtual
Implemented in LCG.
Referenced by check_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
virtual unsigned long int SPRNG::get_seed () const pure virtual
Implemented in LCG, and LCG.
Referenced by main_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
virtual int SPRNG::get_seed () const pure virtual
Implemented in LCG, and LCG.
virtual int SPRNG::get_seed_rng () const pure virtual
Implemented in LCG.
Referenced by ~SPRNG(), and VSPRNG::~VSPRNG().
virtual int SPRNG::init_rng (int , int , int , int) pure virtual
Implemented in LCG.
Referenced by check_gen(), main_gen(), ~SPRNG(), and VSPRNG::~VSPRNG().
The documentation for this class was generated from the following file:
sprng.h