MASPRNG: drivers/main_lcg.cpp File Reference
main_lcg.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "masprng.h"
Macros
#define YES 1
#define NO 0
Functions
int check_gen ()
int main ()
Macro Definition Documentation
#define NO 0
Definition at line 7 of file main_lcg.cpp.
Referenced by check_gen(), and main().
#define YES 1
Definition at line 6 of file main_lcg.cpp.
Referenced by check_gen(), and main().
Function Documentation
int check_gen ()
Definition at line 10 of file main_lcg.cpp.
References SPRNG::get_rn_dbl(), SPRNG::get_rn_flt(), SPRNG::get_rn_int(), SPRNG::init_rng(), NO, selectType(), and YES.
Referenced by main().
 {
   int i, seed, param, scan_ret;
   int tempi, tempi2, correct, result = YES;
   const unsigned int fltmult = 1<<20, dblmult = 1<<30;
   double tempd;
   SPRNG *rng = selectType(1);
   seed = 985456376;
   param = 0;
   rng->init_rng(seed, param);
   correct = YES;
   for(i=0; i<200; i++)
   {
     scan_ret = scanf("%d\n", &tempi);
     if(tempi != (tempi2 = rng->get_rn_int()))
       result = correct = NO;
   }
   if(correct == NO)
     printf("FAILED: Integer generator does not reproduce correct stream.\n\tArithmetic on this machine may not be compatible with this generator.\n");
   else
     printf("PASSED: Integer generator passed the reproducibility test\n");
   correct = YES;
   for(i=0; i<50; i++)
   {
     scan_ret = scanf("%d\n", &tempi);
     tempd = (double) rng->get_rn_flt();
     if(abs((tempi>>11) - (int) (tempd*fltmult)) > 1 )
       result = correct = NO;
   }
   if(correct == NO)
     printf("FAILED: Float generator does not reproduce correct stream.\n\tArithmetic on this machine may not be compatible with this generator.\n");
   else
     printf("PASSED: Float generator passed the reproducibility test\n");
   correct = YES;
   for(i=0; i<50; i++)
   {
     scan_ret = scanf("%d", &tempi);
     tempd = rng->get_rn_dbl();
     if(abs((tempi>>1) - (int) (tempd*dblmult)) > 1 )
       result = correct = NO;
   }
   if(correct == NO)
     printf("FAILED: Double generator does not reproduce correct stream.\n\tArithmetic on this machine may not be compatible with this generator.\n");
   else
     printf("PASSED: Double generator passed the reproducibility test\n");
   return result;
 }
int main ()
Definition at line 74 of file main_lcg.cpp.
References check_gen(), NO, and YES.
 {
   int result=YES;
   printf("Checking make_sprng_seed ...\n");
   if(check_gen() != YES)
     result = NO;
   if(result == YES)
     printf("\nResult:\t PASSED\n\n");
   else
     printf("\nResult:\t FAILED\n\n");
   return 0;
 }