MASPRNG: simd/sse.h File Reference
sse.h File Reference
Functions
SIMD_INT simd_add_i32 (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_add_i64 (const SIMD_INT va, const SIMD_INT vb)
SIMD_FLT simd_add (const SIMD_FLT va, const SIMD_FLT vb)
SIMD_DBL simd_add (const SIMD_DBL va, const SIMD_DBL vb)
SIMD_INT simd_mul_u32 (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_mul_i32 (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_mul_u64 (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_mullo_i32 (const SIMD_INT va, const SIMD_INT vb)
SIMD_FLT simd_mul (const SIMD_FLT va, const SIMD_FLT vb)
SIMD_DBL simd_mul (const SIMD_DBL va, const SIMD_DBL vb)
SIMD_INT simd_or (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_xor (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_and (const SIMD_INT va, const SIMD_INT vb)
int simd_test_zero (const SIMD_INT va, const SIMD_INT vb)
SIMD_INT simd_sll_32 (const SIMD_INT va, const int shft)
SIMD_INT simd_srl_32 (const SIMD_INT va, const int shft)
SIMD_INT simd_sll_64 (const SIMD_INT va, const int shft)
SIMD_INT simd_srl_64 (const SIMD_INT va, const int shft)
SIMD_INT simd_shuffle_32 (const SIMD_INT va, const int ctrl)
void simd_set_zero (SIMD_INT *const va)
void simd_set_zero (SIMD_FLT *const va)
void simd_set_zero (SIMD_DBL *const va)
SIMD_INT simd_set (const int sa)
SIMD_INT simd_set_64 (const int sa)
SIMD_INT simd_set (const unsigned int sa)
SIMD_INT simd_set_64 (const unsigned int sa)
SIMD_INT simd_set (const long int sa)
SIMD_INT simd_set (const unsigned long int sa)
SIMD_FLT simd_set (const float sa)
SIMD_DBL simd_set (const double sa)
SIMD_INT simd_set (const int sa3, const int sa2, const int sa1, const int sa0)
SIMD_INT simd_set (const int sa1, const int sa0)
SIMD_INT simd_set (const unsigned int sa3, const unsigned int sa2, const unsigned int sa1, const unsigned int sa0)
SIMD_INT simd_set (const unsigned int sa1, const unsigned int sa0)
SIMD_INT simd_set (const long int sa1, const long int sa0)
SIMD_INT simd_set (const unsigned long int sa1, const unsigned long int sa0)
SIMD_FLT simd_set (const float sa3, const float sa2, const float sa1, const float sa0)
SIMD_DBL simd_set (const double sa1, const double sa0)
SIMD_INT simd_set (const int *const sa, const int n)
SIMD_INT simd_set (const unsigned int *const sa, const int n)
SIMD_INT simd_set (const long int *const sa, const int n)
SIMD_INT simd_set (const unsigned long int *const sa, const int n)
SIMD_FLT simd_cvt_f64_f32 (const SIMD_DBL va)
SIMD_FLT simd_cvt_u64_f32 (const SIMD_INT va)
SIMD_DBL simd_cvt_u64_f64 (const SIMD_INT va)
SIMD_INT simd_load (const int *const sa)
SIMD_INT simd_load (const unsigned int *const sa)
SIMD_INT simd_load (const long int *const sa)
SIMD_INT simd_load (const unsigned long int *const sa)
SIMD_FLT simd_load (const float *const sa)
SIMD_DBL simd_load (const double *const sa)
void simd_store (int *const sa, const SIMD_INT va)
void simd_store (unsigned int *const sa, const SIMD_INT va)
void simd_store (long int *const sa, const SIMD_INT va)
void simd_store (unsigned long int *const sa, const SIMD_INT va)
void simd_store (float *const sa, const SIMD_FLT va)
void simd_store (double *const sa, const SIMD_DBL va)
void simd_print (const char *const, const SIMD_INT)
void simd_print (const char *const, const SIMD_FLT)
void simd_print (const char *const, const SIMD_DBL)
Function Documentation
SIMD_FLT simd_add (const SIMD_FLT va, const SIMD_FLT vb) inline
Definition at line 46 of file sse.h.
Referenced by VLCG::get_rn_dbl().
 { return _mm_add_ps(va, vb); }
SIMD_DBL simd_add (const SIMD_DBL va, const SIMD_DBL vb) inline
Definition at line 49 of file sse.h.
 { return _mm_add_pd(va, vb); }
SIMD_INT simd_add_i32 (const SIMD_INT va, const SIMD_INT vb) inline
Definition at line 40 of file sse.h.
Referenced by VLCG::multiply().
 { return _mm_add_epi32(va, vb); }
SIMD_INT simd_add_i64 (const SIMD_INT va, const SIMD_INT vb) inline
Definition at line 43 of file sse.h.
Referenced by VLCG::multiply().
 { return _mm_add_epi64(va, vb); }
SIMD_INT simd_and (const SIMD_INT va, const SIMD_INT vb) inline
Definition at line 109 of file sse.h.
Referenced by VLCG::init_rng(), and VLCG::multiply().
 { return _mm_and_si128(va, vb); }
SIMD_FLT simd_cvt_f64_f32 (const SIMD_DBL va) inline
Convert packed double-precision floating-point elements to packed single-precision floating-point elements.
Definition at line 260 of file sse.h.
 { return _mm_cvtpd_ps(va); }
SIMD_FLT simd_cvt_u64_f32 (const SIMD_INT va) inline
Convert unsigned 64-bit integers to 32-bit floating-point elements. NOTE: type conversion performed with scalar FPU since SSE does not support 64-bit integer conversions.
Definition at line 267 of file sse.h.
Referenced by VLCG::get_rn_flt().
 {
     unsigned long int sa[2] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     float fa[4] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     _mm_store_si128((SIMD_INT *)sa, va);
     fa[0] = (float)sa[0];
     fa[1] = 0.0;
     fa[2] = (float)sa[1];
     fa[3] = 0.0;
     return _mm_load_ps(fa);
 }
SIMD_DBL simd_cvt_u64_f64 (const SIMD_INT va) inline
Convert unsigned 64-bit integers to 64-bit floating-point elements. NOTE: type conversion performed with scalar FPU since SSE does not support 64-bit integer conversions.
Definition at line 283 of file sse.h.
Referenced by VLCG::get_rn_dbl().
 {
     unsigned long int sa[2] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     double fa[2] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     _mm_store_si128((SIMD_INT *)sa, va);
     fa[0] = (double)sa[0];
     fa[1] = (double)sa[1];
     return _mm_load_pd(fa);
 }
SIMD_INT simd_load (const int *const sa) inline
Definition at line 297 of file sse.h.
Referenced by VLCG::get_rn_dbl(), and VLCG::init_rng().
 { return _mm_load_si128((SIMD_INT *)sa); }
SIMD_INT simd_load (const unsigned int *const sa) inline
Definition at line 300 of file sse.h.
 { return _mm_load_si128((SIMD_INT *)sa); }
SIMD_INT simd_load (const long int *const sa) inline
Definition at line 303 of file sse.h.
 { return _mm_load_si128((SIMD_INT *)sa); }
SIMD_INT simd_load (const unsigned long int *const sa) inline
Definition at line 306 of file sse.h.
 { return _mm_load_si128((SIMD_INT *)sa); }
SIMD_FLT simd_load (const float *const sa) inline
Definition at line 309 of file sse.h.
 { return _mm_load_ps(sa); }
SIMD_DBL simd_load (const double *const sa) inline
Definition at line 312 of file sse.h.
 { return _mm_load_pd(sa); }
SIMD_FLT simd_mul (const SIMD_FLT va, const SIMD_FLT vb) inline
Definition at line 93 of file sse.h.
Referenced by VLCG::get_rn_dbl(), and VLCG::get_rn_flt().
 { return _mm_mul_ps(va, vb); }
SIMD_DBL simd_mul (const SIMD_DBL va, const SIMD_DBL vb) inline
Definition at line 96 of file sse.h.
 { return _mm_mul_pd(va, vb); }
SIMD_INT simd_mul_i32 (const SIMD_INT va, const SIMD_INT vb) inline
Multiply low signed 32-bit integers from each packed 64-bit elements and store the signed 64-bit results
Definition at line 63 of file sse.h.
 { return _mm_mul_epi32(va, vb); }
SIMD_INT simd_mul_u32 (const SIMD_INT va, const SIMD_INT vb) inline
Multiply low unsigned 32-bit integers from each packed 64-bit elements and store the unsigned 64-bit results
Definition at line 56 of file sse.h.
 { return _mm_mul_epu32(va, vb); }
SIMD_INT simd_mul_u64 (const SIMD_INT va, const SIMD_INT vb) inline
Perform 64-bit integer multiplication using 32-bit integers since SSE does not supports 64-bit integer multiplication. x64 * y64 = (xl * yl) + (xl * yh + xh * yl) * 2^32 NOTE: requires at least SSE 4.1 for _mm_mullo_epi32()
Definition at line 72 of file sse.h.
Referenced by VLCG::multiply().
 {
     SIMD_INT vshf, vh;
     vshf = _mm_shuffle_epi32(vb, 0xB1); // shuffle multiplier
     vh = _mm_mullo_epi32(va, vshf);     // xl * yh, xh * yl
     vshf = _mm_slli_epi64(vh, 0x20);    // shift << 32
     vh = _mm_add_epi64(vh, vshf);       // h = h1 + h2
     vshf = _mm_set1_epi64x(0xFFFFFFFF00000000UL);
     vh = _mm_and_si128(vh, vshf);       // h & 0xFFFFFFFF00000000
     const SIMD_INT vl = _mm_mul_epu32(va, vb);         // l = xl * yl
     return _mm_add_epi64(vl, vh);       // l + h
 }
SIMD_INT simd_mullo_i32 (const SIMD_INT va, const SIMD_INT vb) inline
Multiply packed 32-bit integers, produce intermediate 64-bit integers, and store the low 32-bit results NOTE: requires at least SSE 4.1 for _mm_mullo_epi32()
Definition at line 90 of file sse.h.
Referenced by VLCG::multiply().
 { return _mm_mullo_epi32(va, vb); }
SIMD_INT simd_or (const SIMD_INT va, const SIMD_INT vb) inline
Definition at line 103 of file sse.h.
Referenced by VLCG::get_rn_int(), and VLCG::init_rng().
 { return _mm_or_si128(va, vb); }
void simd_print (const char * const, const SIMD_INT)
Definition at line 9 of file sse.cpp.
References simd_store().
Referenced by VLCG::init_rng(), and simd_store().
 {
     int itmp[SIMD_NUM_32BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(itmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_32BIT; ++i)
       printf("%d\t", itmp[i]);
     printf("\n");
     unsigned int utmp[SIMD_NUM_32BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(utmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_32BIT; ++i)
       printf("%u\t", utmp[i]);
     printf("\n");
     unsigned long int lutmp[SIMD_NUM_64BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(lutmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_64BIT; ++i)
       printf("%lu\t", lutmp[i]);
     printf("\n");
 }
void simd_print (const char * const, const SIMD_FLT)
Definition at line 34 of file sse.cpp.
References simd_store().
 {
     float tmp[SIMD_NUM_32BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(tmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_32BIT; ++i)
       printf("%f\t", tmp[i]);
     printf("\n");
 }
void simd_print (const char * const, const SIMD_DBL)
Definition at line 45 of file sse.cpp.
References simd_store().
 {
     double tmp[SIMD_NUM_64BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(tmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_64BIT; ++i)
       printf("%f\t", tmp[i]);
     printf("\n");
 }
SIMD_INT simd_set (const int sa) inline
Definition at line 161 of file sse.h.
Referenced by VLCG::get_rn_dbl(), VLCG::get_rn_flt(), VLCG::init_rng(), init_simd_masks(), VLCG::multiply(), and VLCG::VLCG().
 { return _mm_set1_epi32(sa); }
SIMD_INT simd_set (const unsigned int sa) inline
Definition at line 165 of file sse.h.
 { return _mm_set1_epi32(sa); }
SIMD_INT simd_set (const long int sa) inline
Definition at line 169 of file sse.h.
 { return _mm_set1_epi64x(sa); }
SIMD_INT simd_set (const unsigned long int sa) inline
Definition at line 171 of file sse.h.
 { return _mm_set1_epi64x(sa); }
SIMD_FLT simd_set (const float sa) inline
Definition at line 173 of file sse.h.
 { return _mm_set1_ps(sa); }
SIMD_DBL simd_set (const double sa) inline
Definition at line 175 of file sse.h.
 { return _mm_set1_pd(sa); }
SIMD_INT simd_set (const int sa3, const int sa2, const int sa1, const int sa0) inline
Definition at line 177 of file sse.h.
 { return _mm_set_epi32(sa3, sa2, sa1, sa0); }
SIMD_INT simd_set (const int sa1, const int sa0) inline
Definition at line 179 of file sse.h.
 { return _mm_set_epi64x(sa1, sa0); }
SIMD_INT simd_set (const unsigned int sa3, const unsigned int sa2, const unsigned int sa1, const unsigned int sa0) inline
Definition at line 181 of file sse.h.
 { return _mm_set_epi32(sa3, sa2, sa1, sa0); }
SIMD_INT simd_set (const unsigned int sa1, const unsigned int sa0) inline
Definition at line 183 of file sse.h.
 { return _mm_set_epi64x(sa1, sa0); }
SIMD_INT simd_set (const long int sa1, const long int sa0) inline
Definition at line 185 of file sse.h.
 { return _mm_set_epi64x(sa1, sa0); }
SIMD_INT simd_set (const unsigned long int sa1, const unsigned long int sa0) inline
Definition at line 187 of file sse.h.
 { return _mm_set_epi64x(sa1, sa0); }
SIMD_FLT simd_set (const float sa3, const float sa2, const float sa1, const float sa0) inline
Definition at line 189 of file sse.h.
 { return _mm_set_ps(sa3, sa2, sa1, sa0); }
SIMD_DBL simd_set (const double sa1, const double sa0) inline
Definition at line 191 of file sse.h.
 { return _mm_set_pd(sa1, sa0); }
SIMD_INT simd_set (const int *const sa, const int n) inline
Set vector given an array. This is the general form but too involved compared to direct form.
Set vector given an array. Only required for non-contiguous 32-bit elements due to in-between padding, 64-bit elements can use load instructions.
Definition at line 219 of file sse.h.
 {
     if (n == 2)
         return _mm_set_epi64x(sa[1], sa[0]);
     else if (n == 4)
         return _mm_load_si128((SIMD_INT *)sa);
     else
         return _mm_setzero_si128();
 }
SIMD_INT simd_set (const unsigned int *const sa, const int n) inline
Definition at line 228 of file sse.h.
 {
     if (n == 2)
         return _mm_set_epi64x(sa[1], sa[0]);
     else if (n == 4)
         return _mm_load_si128((SIMD_INT *)sa);
     else
         return _mm_setzero_si128();
 }
SIMD_INT simd_set (const long int *const sa, const int n) inline
Definition at line 237 of file sse.h.
 {
     if (n == 2)
         return _mm_set_epi64x(sa[1], sa[0]);
     else
         return _mm_setzero_si128();
 }
SIMD_INT simd_set (const unsigned long int *const sa, const int n) inline
Definition at line 244 of file sse.h.
 {
     if (n == 2)
         return _mm_set_epi64x(sa[1], sa[0]);
     else
         return _mm_setzero_si128();
 }
SIMD_INT simd_set_64 (const int sa) inline
Definition at line 163 of file sse.h.
Referenced by VLCG::init_rng().
 { return _mm_set1_epi64x(sa); }
SIMD_INT simd_set_64 (const unsigned int sa) inline
Definition at line 167 of file sse.h.
 { return _mm_set1_epi64x(sa); }
void simd_set_zero (SIMD_INT *const va) inline
Definition at line 149 of file sse.h.
Referenced by VLCG::VLCG().
 { *va = _mm_setzero_si128(); }
void simd_set_zero (SIMD_FLT *const va) inline
Definition at line 152 of file sse.h.
 { *va = _mm_setzero_ps(); }
void simd_set_zero (SIMD_DBL *const va) inline
Definition at line 155 of file sse.h.
 { *va = _mm_setzero_pd(); }
SIMD_INT simd_shuffle_32 (const SIMD_INT va, const int ctrl) inline
Shuffle 32-bit integers using control value
Definition at line 138 of file sse.h.
 { return _mm_shuffle_epi32(va, ctrl); }
SIMD_INT simd_sll_32 (const SIMD_INT va, const int shft) inline
Definition at line 123 of file sse.h.
Referenced by VLCG::get_rn_int(), VLCG::init_rng(), and VLCG::multiply().
 { return _mm_slli_epi32(va, shft); }
SIMD_INT simd_sll_64 (const SIMD_INT va, const int shft) inline
Definition at line 129 of file sse.h.
Referenced by VLCG::init_rng().
 { return _mm_slli_epi64(va, shft); }
SIMD_INT simd_srl_32 (const SIMD_INT va, const int shft) inline
Definition at line 126 of file sse.h.
Referenced by VLCG::get_rn_int(), VLCG::init_rng(), and VLCG::multiply().
 { return _mm_srli_epi32(va, shft); }
SIMD_INT simd_srl_64 (const SIMD_INT va, const int shft) inline
Definition at line 132 of file sse.h.
Referenced by VLCG::get_rn_int().
 { return _mm_srli_epi64(va, shft); }
void simd_store (int *const sa, const SIMD_INT va) inline
Definition at line 319 of file sse.h.
Referenced by check_gen(), VLCG::get_rn_dbl(), main_gen(), and simd_print().
 { _mm_store_si128((SIMD_INT *)sa, va); }
void simd_store (unsigned int *const sa, const SIMD_INT va) inline
Definition at line 322 of file sse.h.
 { _mm_store_si128((SIMD_INT *)sa, va); }
void simd_store (long int *const sa, const SIMD_INT va) inline
Definition at line 325 of file sse.h.
 { _mm_store_si128((SIMD_INT *)sa, va); }
void simd_store (unsigned long int *const sa, const SIMD_INT va) inline
Definition at line 328 of file sse.h.
 { _mm_store_si128((SIMD_INT *)sa, va); }
void simd_store (float *const sa, const SIMD_FLT va) inline
Definition at line 331 of file sse.h.
 { _mm_store_ps(sa, va); }
void simd_store (double *const sa, const SIMD_DBL va) inline
Definition at line 334 of file sse.h.
References simd_print().
 { _mm_store_pd(sa, va); }
int simd_test_zero (const SIMD_INT va, const SIMD_INT vb) inline
Definition at line 113 of file sse.h.
Referenced by VLCG::init_rng().
 { return _mm_test_all_zeros(va, vb); }
SIMD_INT simd_xor (const SIMD_INT va, const SIMD_INT vb) inline
Definition at line 106 of file sse.h.
Referenced by VLCG::init_rng().
 { return _mm_xor_si128(va, vb); }