MASPRNG: utils/utils.cpp File Reference
utils.cpp File Reference
Functions
int setOmpEnv (const int num_threads)
int printSIMDconf ()
void printSysconf ()
long int getNumProcOnline ()
long int getPageSz ()
long int getL1Sz ()
long int getL1LineSz ()
long int getL1Assoc ()
long int getL2Sz ()
long int getL2LineSz ()
long int getL2Assoc ()
long int getL3Sz ()
long int getL3LineSz ()
long int getL3Assoc ()
Function Documentation
long int getL1Assoc ()
Get the associativity of L1 data cache
Definition at line 104 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL1_DCACHE_ASSOC); }
long int getL1LineSz ()
Get the line size in bytes of L1 data cache
Definition at line 101 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL1_DCACHE_LINESIZE); }
long int getL1Sz ()
Get the size in bytes of L1 data cache
Definition at line 98 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL1_DCACHE_SIZE); }
long int getL2Assoc ()
Get the associativity of L2 cache
Definition at line 113 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL2_CACHE_ASSOC); }
long int getL2LineSz ()
Get the line size in bytes of L2 cache
Definition at line 110 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL2_CACHE_LINESIZE); }
long int getL2Sz ()
Get the size in bytes of L2 cache
Definition at line 107 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL2_CACHE_SIZE); }
long int getL3Assoc ()
Get the associativity of L3 cache
Definition at line 122 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL3_CACHE_ASSOC); }
long int getL3LineSz ()
Get the line size in bytes of L3 cache
Definition at line 119 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL3_CACHE_LINESIZE); }
long int getL3Sz ()
Get the size in bytes of L3 cache
Definition at line 116 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_LEVEL3_CACHE_SIZE); }
long int getNumProcOnline ()
Get the number of processors currently online (available)
Definition at line 90 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_NPROCESSORS_ONLN); }
long int getPageSz ()
Get the size of page in bytes
Definition at line 94 of file utils.cpp.
Referenced by printSysconf().
 { return sysconf(_SC_PAGESIZE); }
int printSIMDconf ()
Detect CPU SIMD features
Definition at line 40 of file utils.cpp.
 {
 #if GNUC_VERSION > 40800
     if (__builtin_cpu_supports("sse"))
         puts("SSE");
     if (__builtin_cpu_supports("sse2"))
         puts("SSE2");
     if (__builtin_cpu_supports("sse3"))
         puts("SSE3");
     if (__builtin_cpu_supports("ssse3"))
         puts("SSSE3");
     if (__builtin_cpu_supports("sse4.1"))
         puts("SSE4.1");
     if (__builtin_cpu_supports("sse4.2"))
         puts("SSE4.2");
     if (__builtin_cpu_supports("avx"))
         puts("AVX");
     if (__builtin_cpu_supports("avx2"))
         puts("AVX2");
     if (__builtin_cpu_supports("avx512f"))
         puts("AVX512F");
 #endif
     return 0;
 }
void printSysconf ()
Print some system configurations
Definition at line 67 of file utils.cpp.
References getL1Assoc(), getL1LineSz(), getL1Sz(), getL2Assoc(), getL2LineSz(), getL2Sz(), getL3Assoc(), getL3LineSz(), getL3Sz(), getNumProcOnline(), and getPageSz().
 {
     printf("Number of processors online = %ld\n", getNumProcOnline());
     printf("Page size = %ld\n", getPageSz());
     printf("L1 data cache size = %ld\n", getL1Sz());
     printf("L1 data cache associativity = %ld\n", getL1LineSz());
     printf("L1 data cache line size = %ld\n", getL1Assoc());
     printf("L2 cache size = %ld\n", getL2Sz());
     printf("L2 cache associativity = %ld\n", getL2LineSz());
     printf("L2 cache line size = %ld\n", getL2Assoc());
     printf("L3 cache size = %ld\n", getL3Sz());
     printf("L3 cache associativity = %ld\n", getL3LineSz());
     printf("L3 cache line size = %ld\n", getL3Assoc());
 #if defined(_OPENMP)
     printf("OMP threads = %d of %d\n", omp_get_num_threads(), omp_get_max_threads());
 #endif
 }
int setOmpEnv (const int)
Configure OpenMP environment
Definition at line 18 of file utils.cpp.
 {
     int nt;
 #if defined(_OPENMP)
     if (getenv("OMP_NUM_THREADS"))
         nt = (num_threads > 0) ? (num_threads) : OMP_NUM_THREADS;
     else
         nt = (num_threads > 0) ? (num_threads) : 1;
     omp_set_num_threads(nt);
  #if defined(__INTEL_COMPILER)
     setenv("KMP_AFFINITY", "granularity=fine,scatter", 1);
  #endif
 #else
     nt = (num_threads > 0) ? (num_threads) : 1;
 #endif
     return nt;
 }