MASPRNG: simd/sse.cpp File Reference
sse.cpp File Reference
#include <cstdio>
#include "sse.h"
Macros
#define SIMD_NUM_32BIT (SIMD_WIDTH_BYTES/4)
#define SIMD_NUM_64BIT (SIMD_WIDTH_BYTES/8)
Functions
void simd_print (const char *const str, const SIMD_INT va)
void simd_print (const char *const str, const SIMD_FLT va)
void simd_print (const char *const str, const SIMD_DBL va)
Macro Definition Documentation
#define SIMD_NUM_32BIT (SIMD_WIDTH_BYTES/4)
number of 32-bit values per vector register
Definition at line 5 of file sse.cpp.
Referenced by simd_print().
#define SIMD_NUM_64BIT (SIMD_WIDTH_BYTES/8)
number of 64-bit values per vector register
Definition at line 6 of file sse.cpp.
Referenced by simd_print().
Function Documentation
void simd_print (const char *const str, const SIMD_INT va)
Definition at line 9 of file sse.cpp.
References SIMD_NUM_32BIT, SIMD_NUM_64BIT, simd_store(), and SIMD_WIDTH_BYTES.
Referenced by simd_store().
 {
     int itmp[SIMD_NUM_32BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(itmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_32BIT; ++i)
       printf("%d\t", itmp[i]);
     printf("\n");
     unsigned int utmp[SIMD_NUM_32BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(utmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_32BIT; ++i)
       printf("%u\t", utmp[i]);
     printf("\n");
     unsigned long int lutmp[SIMD_NUM_64BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(lutmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_64BIT; ++i)
       printf("%lu\t", lutmp[i]);
     printf("\n");
 }
void simd_print (const char *const str, const SIMD_FLT va)
Definition at line 34 of file sse.cpp.
References SIMD_NUM_32BIT, simd_store(), and SIMD_WIDTH_BYTES.
 {
     float tmp[SIMD_NUM_32BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(tmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_32BIT; ++i)
       printf("%f\t", tmp[i]);
     printf("\n");
 }
void simd_print (const char *const str, const SIMD_DBL va)
Definition at line 45 of file sse.cpp.
References SIMD_NUM_64BIT, simd_store(), and SIMD_WIDTH_BYTES.
 {
     double tmp[SIMD_NUM_64BIT] __attribute__ ((aligned(SIMD_WIDTH_BYTES)));
     simd_store(tmp, va);
     printf("%s", str);
     for (int i = 0; i < SIMD_NUM_64BIT; ++i)
       printf("%f\t", tmp[i]);
     printf("\n");
 }